### ISSUE TITLE
Remove div that contain row class for the toolbar

### ISSUE THREAD

**Issue by hadihaber** [hadihaber/AB-modifications#1]
![sc1](https://cloud.githubusercontent.com/assets/16542293/23300494/75354986-fa8e-11e6-863c-94393f11677e.PNG)

**Comment by FadiZahhar** [comment]
fixed by adding a class row on the dropdownbox in OnlineApplication.html in the GridSystem of boostrap.
Also make sure that the the layout of checkboxes is default_inline.
