### ISSUE TITLE
3d link to be directly link without popup 

### ISSUE THREAD

**Issue by hadihaber** [hadihaber/AB-modifications#3]
![sc3](https://cloud.githubusercontent.com/assets/16542293/23300798/e554aa1c-fa8f-11e6-84aa-eb378143bc01.PNG)

**Comment by FadiZahhar** [comment]
it is done, 
to deploy it I created in customsetting in sitefinity a content
Key: CustomServices
Value: url

also make sure that it is translated on arabic. but the fact arabic link is the same link as english
